baseURL = "https://goremotefest.com/"
languageCode = "en-US"
title = "Go Remote Fest"
theme = "goremoteconf"
enableRobotsTXT = true
googleAnalytics = ""

spearkes = false
schedule = false
sponsors = false

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
    defaultDescription = "Go Remote Fest, is a remote conference focused on Go. Join us for one sunday of great Go content with awesomes speakers from all world from your own Home."

#[[menu.main]]
#    name = "Home"
#    url = "#"
#    identifier = "home"
#    weight = 100

#[[menu.main]]
#    name = "Speakers"
#    url = "#"
#    identifier = "speakers"
#    weight = 200
#
#[[menu.main]]
#    name = "Schedule"
#    url = "#"
#    identifier = "schedule"
#    weight = 300
#
#[[menu.main]]
#    name = "Sponsors"
#    url = "#"
#    identifier = "sponsors"
#    weight = 400
#
#[[menu.main]]
#    name = "COC"
#    url = "/coc"
#    identifier = "coc"
#    weight = 500

## Social Accounts
[params.social]
	twitter = "goremotefest"